### ISSUE TITLE
Anything specific problematic or need further testing?

### ISSUE THREAD

**Issue by zimmra** [juanboro/cync2mqtt#1]
First off, this looks extremely promising and can't wait to dive into it.

Anything specific that is causing problems for you or that you would like further testing on? I have a variety of both tunable-white and RGBW BTLE bulbs, both A19 and BR30 to test this with.

Should C-Reach be removed from Cync configuration/site? That's how I am currently integrating but would love to remove it. 

I've also got a couple of their smart plugs too, they're not in my Cync config as not currently compatible with them but not sure if having either the C-Reach or these smart plugs on the mesh would help strengthen it

**Comment by juanboro** [comment]
Thanks - yeah - would be good to know if the RGBW and tunable bulbs work --- I don't have any myself... but they _should_ work.  I think it should know to skip the C-reach bridge - but don't know for sure.  I have the plug wifi bridge that was in the starter pack... it seems to work right (the wifi part gets excluded).  I'm still having trouble in some cases with robustly handling when the mesh is unreachable.
