### ISSUE TITLE
Color temperature slider does not persist/represent actual state

### ISSUE THREAD

**Issue by zimmra** [juanboro/cync2mqtt#13]
The color temp slider functions when you interact with it, but it always displays 153 (coolest temp) when first opening the entity. 
![IMG_0464](https://user-images.githubusercontent.com/28514085/147031315-3f7b6cbf-c204-4baf-b4ae-5e8fbaff30d9.png)

Not sure if it's related, but when made into a light group (via group platform) both the brightness slider and color temp slider are slid all the way to the left. Both work, but never represent the actual state

**Comment by juanboro** [comment]
I can confirm it's related on the light group.  When I enable temperature on my lights (which they don't support) - the light group stops showing proper status for brightness as well as temperature.

I've pushed in one more debug item -- can you see what running with debug returns for the pub_worker device_status?  Here is what I see on my light that doesn't support temperature (it returns 255 as the color_temp):
```
2021-12-22 21:21:18,044 - cync2mqtt - DEBUG - pub_worker - device_status: DeviceStatus(name='D1284D352087', id=1, brightness=0, rgb=False, red=0, green=0, blue=0, color_temp=255)
```

**Comment by zimmra** [comment]
brightness reports back in that field, but temperature is reporting 1-100
`2021-12-23 06:40:14,727 - cync2mqtt - DEBUG - pub_worker - device_status: DeviceStatus(name='44ADB1815E67', id=24, brightness=12, rgb=False, red=0, green=0, blue=0, color_temp=100)`

**Comment by juanboro** [comment]
Ok -- I took a look at the HA json schema docs again ... should be fixed now :-).  Give it a try.

**Comment by zimmra** [comment]
Seems to work, groups work properly for me now, and both group & individual temp and brightness sliders represent actual state.
