### ISSUE TITLE
tunable white state information in HA

### ISSUE THREAD

**Issue by mrja** [juanboro/cync2mqtt#15]
hey!  first of all, thanks so much for your effort in making what we have so far into something functional!

I seem to be having issues with my selection of LED strips and bulbs, each with a tunable CW/WW option in addition to setting an RGB value.  while RGB settings work without a hitch, whenever I use a CW/WW setting through the UI or by way of service calls I get a result where the lights respond but the state in HA breaks parity and in the UI, its brightness jumps away from the click-drag to show 0, and while the UI color temperature handle doesn't jump away, revisiting the entity in the UI again shows it to be doing the same thing (state value of 0).

I made an effort to clumsily hack things into behaving properly but I lack an understanding of how HA's workflow functions, let alone what is in motion with your reverse engineering work here.  While looking through things I did see what I thought to be mistakes in feature naming, but sadly I don't have anything to contribute besides this description and a willingness to help however I can.

As it stands I'm still tickled these otherwise pieces of trash can be utilized!  However, when it comes to involving these lights in scenes and the like the glitch is a problem. seeing as they're intended to be primarily used for their white settings by how much brighter they get, I hope there's value involved with addressing this bug :)  thanks again!

**Comment by juanboro** [comment]
I'll take a look --- I need to refresh my memory on how this worked myself.

**Comment by juanboro** [comment]
I've pushed a guess out how to make it report this right.  I only have the basic brightness only lights so alot is guess work on the color stuff based on how it works with other lights.

**Comment by mrja** [comment]
sorry it took me this long to notice-  i'll give this a shot as soon as i have some time to spare.  i'll keep my fingers and toes crossed!

**Comment by mrja** [comment]
at first glance it seems everything is the same as it was-  i do think i got the updated source, but i have the same insight as before (sorry!)

if this helps, when I execute a service call to use a white, all I have to declare is 'color_temp' and 'brightness', ala:

```
  action:
  - service: light.turn_on
    data:
      color_temp: 316
      brightness: 255
    target:
      entity_id:
      - light.back_wall
```
...but what I don't know is how HA listens to what goes on but then fails to properly set the state of the device.

**Comment by juanboro** [comment]
I'm still trying to take a look at this (need to get a few cycles to spend again)... I need to remind myself how the HA mqtt stuff works.

**Comment by mrja** [comment]
any luck?  feel free to hit me up if you'd care to link up and work on anything together.  i'm not sure how much help i'd ultimately be but i'm very motivated to learn.

**Comment by juanboro** [comment]
First thing to try -- do a run with --log-level DEBUG

When you change the values in HA (or the app) - you should see it echoing a message like this in response:
2022-09-09 19:18:09,870 - cync2mqtt - DEBUG - pub_worker - device_status: DeviceStatus(name='DXXX', id=2, brightness=50, rgb=False, red=0, green=0, blue=0, color_temp=255)
2022-09-09 19:18:09,870 - cync2mqtt - DEBUG - pub_worker  mqtt publish: acyncmqtt/status/DXXX/2  {"brightness": 50, "state": "ON"}

What do those logs look like (and the values before them)?  What we need to see is whether it is seeing the right values and just getting sent to HA wrong, or just are not being read properly in the first place.

**Comment by juanboro** [comment]
I think this now works correctly... I spent some time debugging this with my newer lights this weekend and it seems to be doing the right thing now.
