### ISSUE TITLE
Error at yaml configuration

### ISSUE THREAD

**Issue by ctclab123** [juanboro/cync2mqtt#16]
Hello!

Thank you so much for your work here. I have been trying for months to get my GE devices successfully integrated with my home assistant installation. 

I followed your instructions to install cync2mqtt on my raspberry pi zero w. All went well, I was able to create the virtual environment and successfully authenticate. Right after authentication, it threw an error relating to (what I believe) is the creation of the configuration yaml file. Error is included below:

---
Traceback (most recent call last):
  File "/home/pi/venv/cync2mqtt/bin/get_cync_config_from_cloud", line 30, in <module>
    main()
  File "/home/pi/venv/cync2mqtt/bin/get_cync_config_from_cloud", line 22, in main
    yaml.dump(acync.app_meshinfo_to_configdict(meshinfo),fp)
  File "/home/pi/venv/cync2mqtt/lib/python3.9/site-packages/acync/__init__.py", line 98, in app_meshinfo_to_configdict
    bulbdevice=device(None,bulb['displayName'], id, bulb['mac'],bulb['deviceType'])
KeyError: 'mac'
---

I appreciate any help that you might be able to provide. My apologies if this is a simple question/I should know this already.

Thank you!

**Comment by juanboro** [comment]
I'll take a look.  It's been awhile since I tried to download the config from the cloud.

**Comment by ctclab123** [comment]
Thank you! I also have my device mac addresses from working with python laurel. Is it possible to construct a config file from that information?

**Comment by juanboro** [comment]
Yes -- see the file cync_mesh_example.yaml --- see the example file: cync_mesh_example.yaml.  I'm offline for a week - but when I'm back I'll add some code to put in empty values for the fields not returned from the cloud so it doesn't throw an exception.

**Comment by ctclab123** [comment]
Thank you very much

**Comment by juanboro** [comment]
I think I've finally fixed this.... sorry about the delay.  Can reopen this if still a problem.
