### ISSUE TITLE
No MQTT Messages Sent

### ISSUE THREAD

**Issue by zimmra** [juanboro/cync2mqtt#5]
Mostly radio silence at my broker.  Not quite sure where to begin at troubleshooting beyond checking what logs I've already checked. 

For reference:
xx.161 is the RPi running cync2mqtt
xx.156 is HASS

I see the connection in my Mosquitto Broker HA addon logs
```
1639553254: New connection from 192.168.2.161 on port 1883
```

I see the connection in my RPi (cync2mqtt host) Mosquitto logs (/var/log/mosquitto/mosquitto.log)
```
1639553618: New connection from 192.168.2.156:51642 on port 1883.
1639553618: New client connected from 192.168.2.156:51642 as auto-00F81E2D-0CAE-4896-C603-088AD0B1BD26 (p2, c1, k60, u'addons').
```

I can see messages I send, but don't see anything generated/reported by cync2mqtt

With cync2mqtt running on host @ IP 192.168.2.161 this is what I get:

HASS (via Terminal addon):  
```
mosquitto_sub -h 192.168.2.161 -v -t 'acyncmqtt/#' -t 'homeassistant/#'


```

Via SSH (have tried this part from the RPi, from my HASS instance, and from a third PC all with the same result):
```
mosquitto_pub  -h 192.168.2.161 -t 'acyncmqtt/devices' -m get
```

Output in (listening) HASS Terminal:
```
acyncmqtt/devices get
```

Let me know if there's any other logs that might be useful. 

Very well could be due to the changes I made at https://github.com/juanboro/cync2mqtt/pull/4, but without those it would not connect at all.

**Comment by zimmra** [comment]
Messing around with topic filters I noticed this, might have previously been drowned out by other mqtt 'noise' in the log

This is from mosquitto_sub  to my HASS/MQTT Broker instance (xx.156) 
```
mosquitto_sub -h 192.168.2.156 -v -t 'acyncmqtt/#' -t 'homeassistant/#'
```

Output:
```
acyncmqtt/availability/44ADB1815E67/1 offline
acyncmqtt/availability/44ADB1815E67/2 offline
acyncmqtt/availability/44ADB1815E67/3 offline
...
```

In more messing around, I removed the `supports_temperature: true` from one of the lamp's attributes and while not working, things changed.
While in a mosquito_sub (to my HASS/Mosquitto Broker) I see this generated, I assume it is for this lamp

```
homeassistant/light/[redacted string]/[redacted string]_audio/config (null) 
```

And in HASS I see in my MQTT Integration that a light entity corresponding with this lamp has been made as well (but with an 'unavailable' status)

![image](https://user-images.githubusercontent.com/28514085/146151320-a3a4a247-8f05-44b1-ad9a-6df3ca5856a9.png)

So cync2mqtt is able to at least communicate with my HASS/MQTT instance, just isn't seeing/sending over valid information possibly?

**Comment by juanboro** [comment]
Try it now --- I saw the same thing when I merged PR4.  The 2nd part within the actual mesh code didn't need the byte order swap... once I put it back everything worked again.

**Comment by zimmra** [comment]
> Try it now --- I saw the same thing when I merged PR4. The 2nd part within the actual mesh code didn't need the byte order swap... once I put it back everything worked again.

So when I sub to the RPi running cync2mqtt I see the devices now:
[mqtt from cync2mqtt RPi.txt](https://github.com/juanboro/cync2mqtt/files/7725617/mqtt.from.cync2mqtt.RPi.txt)

But in MQTT integration in HASS no new entities are reporting.

In my Mosquitto logs on the HASS machine I see this. The 172.xx should be other addons, but the 192.168.2.161 is the RPi running cync2mqtt
### HASS Mosquitto Addon Logs:
```
1639642422: New connection from 192.168.2.161 on port 1883.
1639642422: New client connected from 192.168.2.161 as amqtt/lrQhiMg>naRlNRj3 (p2, c1, k9).
1639642516: New connection from 192.168.2.161 on port 1883.
1639642516: New client connected from 192.168.2.161 as auto-489CADFB-CDD9-7CDE-F78F-7E4A7764FD89 (p2, c1, k60).
1639642516: Client auto-489CADFB-CDD9-7CDE-F78F-7E4A7764FD89 disconnected.
1639642537: New connection from 172.30.32.2 on port 1883.
1639642537: Socket error on client <unknown>, disconnecting.
1639642602: Socket error on client amqtt/lrQhiMg>naRlNRj3, disconnecting.
1639642657: New connection from 172.30.32.2 on port 1883.
1639642657: Socket error on client <unknown>, disconnecting.
1639642777: New connection from 172.30.32.2 on port 1883.
1639642777: Socket error on client <unknown>, disconnecting.
1639642897: New connection from 172.30.32.2 on port 1883.
1639642897: Socket error on client <unknown>, disconnecting.
1639643017: New connection from 172.30.32.2 on port 1883.
1639643017: Socket error on client <unknown>, disconnecting.
```


Do I need to put any HASS credentials in for cync2mqtt or anything like that to be able to communicate with it? I wouldn't think so, as it was able to get those nebulous (inactive) entities created from my screenshot a few posts back.

**Comment by juanboro** [comment]
Hmmm... the sub looks (mostly) right on the RPI.  The only issue I see there is it looks like with the large number of devices that some of them at the bottom aren't getting set online (race condition).  That logic I'll try to fix tonight.

I need to understand a little bit more about the mosquitto add in... I'll do some googling during breaks today at work.

**Comment by juanboro** [comment]
Ok --- I hopefully fixed the status race.  Your log of the mqtt messages looks good.  It is correctly able to get callback status from the mesh nodes.  Are you able to control the devices via mqtt publish directly?  i.e on mqtt terminal or command line:
```
mosquitto_pub -h mqtt://homeassistant:1883/ -t "acyncmqtt/set/44ADB1815E67/1" -m '{"state": "OFF"}'
mosquitto_pub -h mqtt://homeassistant:1883/ -t "acyncmqtt/set/44ADB1815E67/1" -m '{"state": "ON"}'
```
Do you know if perhaps the HASS distribution changes the [discovery](https://www.home-assistant.io/docs/mqtt/discovery/) topic?  My own install are the docker homeassistant image --- in it the topic prefix is 'homeassistant/' as is in the log.

I assume the [HASS mosquito broker](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md) works similar to standalone mosquito setup if you don't set the credentials, etc.  My own HA setup is at two different locations - each of which have the mosquito broker running on an asus router running entware.

**Comment by juanboro** [comment]
Also --- one more thing to check.  After all these changes - you want to make sure to restart the HA server.  This will re-trigger the discovery.  One thing I just noticed --- is that with the MAC changes - the uniqueIDs changed.  So some of my dashboard customizations broke and needed to be updated with the new entities.

**Comment by zimmra** [comment]
> I need to understand a little bit more about the mosquitto add in
It is just an Eclispse Mosquitto broker docker container AFAIK

I'll check tonight when I get home.

The cync2mqtt RPi.txt is from the following command:
```
mosquitto_sub -h cync2mqttrpi -v -t 'acyncmqtt/#' -t 'homeassistant/#'
```
With cync2mqttrpi being the RPi running solely cync2mqtt. HASS (hostname: homeassistant) is a separate machine. 

If I do the following: `mosquitto_sub -h homeassistant -v -t 'acyncmqtt/#' -t 'homeassistant/#'` I get nothing 
Not sure if that is how it is supposed to be, or indicative of a problem. (I'm pretty new to MQTT, so not always sure what's right or not)

> Do you know if perhaps the HASS distribution changes the discovery topic?

Default discovery topic is homeassistant, default status topic is homeassistant/status

> I assume the HASS mosquito broker works similar to standalone mosquito setup if you don't set the credentials, etc

It setups up users automatically based on your HA users, but I don't believe credentials are required to publish to the topic but perhaps they are. If credentials are needed, where would I put them in?  ~~I don't believe this is the case, as it connects to Mosquitto, but would like to try if the recent changes don't work.~~ The more I read the more I do think this is the case. According to https://amqtt.readthedocs.io/_/downloads/en/stable/pdf/, it looks like I can just modify the mqtt_url parameter to mqtt://user:password@homassistant:1883

**Comment by juanboro** [comment]
Ahh - I see.  Yeah - above looks like the right [URI scheme](https://github.com/mqtt/mqtt.org/wiki/URI-Scheme).   Will be interested to hear how it goes.  That's probably why the mosquito_sub above didn't return anything (didn't authenticate).  Normally you'll at least see homeassistant itself send messages when it goes online or offline.

**Comment by zimmra** [comment]
> Ahh - I see. Yeah - above looks like the right [URI scheme](https://github.com/mqtt/mqtt.org/wiki/URI-Scheme). Will be interested to hear how it goes. That's probably why the mosquito_sub above didn't return anything (didn't authenticate). Normally you'll at least see homeassistant itself send messages when it goes online or offline.

So I am getting a 'more normal' connection message now, this is with the user/pass in the url and the most recent version of cync2mqtt
### Mosquitto Addon Log
```
...
1639709819: New client connected from 192.168.2.161 as amqtt/RGUR0wsz5GYyiD<] (p2, c1, k9, u'hassmqtt').
```
With no follow up disconnect message (like there was previously)

There is still no MQTT messages being sent to my homeassistant host. from my cync2mqtt host  Now when I sub to the homeassistant host (with -u and -P username/password flags) I see my 'normal' MQTT messages from my other services, but nothing from cync2mqtt. It's worth noting when I sub to my cync2mqtt host I no longer see the messages I saw last night, seemingly complete radio silence. 

I added a different MQTT service just to ensure my host could see something new, and it did successfully discover and add that service.

**Comment by zimmra** [comment]
When I restart my HASS (& Mosquitto Broker) host, the cync2mqtt is definitely connected because as that happens it gets 'unhappy'

```
pi@zPI:~ $ sudo systemctl status cync2mqtt
* cync2mqtt.service - cync2mqtt
     Loaded: loaded (/etc/systemd/system/cync2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-16 18:56:58 PST; 20min ago
   Main PID: 798 (cync2mqtt)
      Tasks: 2 (limit: 8771)
        CPU: 1.674s
     CGroup: /system.slice/cync2mqtt.service
             |-798 /home/pi/venv/cync2mqtt/bin/python3 /home/pi/venv/cync2mqtt/bin/cync2mqtt /home/pi/cync_mesh.yaml
             `-801 /home/pi/venv/cync2mqtt/bin/python3 /home/pi/venv/cync2mqtt/bin/cync2mqtt /home/pi/cync_mesh.yaml

Dec 16 19:12:24 zPI cync2mqtt[801]: 2021-12-16 19:12:24,742 - cync2mqtt - ERROR - Unable to publish mqtt message... skipped
Dec 16 19:12:24 zPI cync2mqtt[801]: Client not connected, waiting for it
Dec 16 19:12:24 zPI cync2mqtt[801]: 2021-12-16 19:12:24,743 - cync2mqtt - ERROR - Unable to publish mqtt message... skipped
Dec 16 19:12:24 zPI cync2mqtt[801]: Client not connected, waiting for it
Dec 16 19:12:24 zPI cync2mqtt[801]: 2021-12-16 19:12:24,784 - cync2mqtt - ERROR - Unable to publish mqtt message... skipped
Dec 16 19:12:24 zPI cync2mqtt[801]: Client not connected, waiting for it
Dec 16 19:12:24 zPI cync2mqtt[801]: 2021-12-16 19:12:24,785 - cync2mqtt - ERROR - Unable to publish mqtt message... skipped
Dec 16 19:12:24 zPI cync2mqtt[801]: Client not connected, waiting for it
Dec 16 19:12:24 zPI cync2mqtt[801]: 2021-12-16 19:12:24,787 - cync2mqtt - ERROR - Unable to publish mqtt message... skipped
Dec 16 19:12:30 zPI cync2mqtt[801]: Client not connected, waiting for it
```

After the host reboots it eventually reconnects
```
cync2mqtt.service - cync2mqtt
     Loaded: loaded (/etc/systemd/system/cync2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-16 18:56:58 PST; 22min ago
   Main PID: 798 (cync2mqtt)
      Tasks: 2 (limit: 8771)
        CPU: 3.007s
     CGroup: /system.slice/cync2mqtt.service
             |- 798 /home/pi/venv/cync2mqtt/bin/python3 /home/pi/venv/cync2mqtt/bin/cync2mqtt /home/pi/cync_mesh.yaml
             `-1003 /home/pi/venv/cync2mqtt/bin/python3 /home/pi/venv/cync2mqtt/bin/cync2mqtt /home/pi/cync_mesh.yaml

Dec 16 19:18:00 zPI cync2mqtt[801]: 2021-12-16 19:18:00,541 - cync2mqtt - INFO - Shutting down
Dec 16 19:18:00 zPI cync2mqtt[801]: Client not connected, waiting for it
Dec 16 19:18:02 zPI cync2mqtt[798]: 2021-12-16 19:18:02,726 - cync2mqtt - INFO - Will attempt reconnect in 10 seconds
Dec 16 19:18:12 zPI cync2mqtt[798]: 2021-12-16 19:18:12,737 - cync2mqtt - INFO - Restarting!
Dec 16 19:18:14 zPI cync2mqtt[1003]: 2021-12-16 19:18:14,043 - cync2mqtt - INFO - Unable to connect to mesh mac: A4:C1:38:54:2A:B3
Dec 16 19:18:47 zPI cync2mqtt[1003]: 2021-12-16 19:18:47,144 - cync2mqtt - INFO - Unable to connect to mesh mac for notify: A4:C1:38:4C:BE:>
Dec 16 19:18:51 zPI cync2mqtt[1003]: 2021-12-16 19:18:51,683 - cync2mqtt - INFO - Unable to connect to mesh mac: A4:C1:38:4C:5D:A1
Dec 16 19:18:53 zPI cync2mqtt[1003]: 2021-12-16 19:18:53,511 - cync2mqtt - INFO - Unable to connect to mesh mac: A4:C1:38:65:F6:C6
Dec 16 19:18:56 zPI cync2mqtt[1003]: 2021-12-16 19:18:56,632 - cync2mqtt - INFO - Connected to mesh mac: A4:C1:38:69:66:25
Dec 16 19:18:56 zPI cync2mqtt[1003]: 2021-12-16 19:18:56,633 - cync2mqtt - INFO - Connected to network(s): HASS
```

But still no MQTT messages seen on HASS host

Is there anyway to get cync2mqtt to run verbose? Without seeing what cync2mqtt is trying to do I am not sure where to look to troubleshoot.

**Comment by juanboro** [comment]
>Is there anyway to get cync2mqtt to run verbose? Without seeing what cync2mqtt is trying to do I am not sure where to look to >troubleshoot.
Partially - but there is not much else dumped right now--- you can control the log-level with:
```
~/venv/cync2mqtt/bin/cync2mqtt --log-level DEBUG config.yaml
```

Mainly my recollection is I have it turn on python asyncio debug info.

I've added some more debug lines now - so you should be able to see the mqtt messages it sends and receives.  If you turn on the lights via Alexa or the cync app you should see that their status updates reflected in the logs, i.e: something like:
```
2021-12-17 20:18:58,875 - cync2mqtt - DEBUG - pub_worker  mqtt publish: acyncmqtt/status/D1284D352087/2  {"brightness": 0, "state": "OFF"}
2021-12-17 20:18:59,538 - cync2mqtt - DEBUG - pub_worker  mqtt publish: acyncmqtt/status/D1284D352087/3  {"brightness": 0, "state": "OFF"}
```

**Comment by zimmra** [comment]
Yeah there is something in the Mosquitto broker addon that is interfering, I just don't have any indication as to where the failure is.

If I spin up an eclispe-mosquitto docker on another machine and point cync2mqtt at it, that MQTT instance sees it right away. Auth is turned on in this instance too.
I'll have to dive deeper to see what could be causing this. Unfortunate, as I would imagine if this got to the point where the 'typical' HASS user could use it then it not working with the native mosquitto addon is a problem.

**Comment by Dperrigo18** [comment]
I also believe that there is a issue with the native mosquito add-on one home assistant.
I found an alternative here [here](https://github.com/nao-pon/home-assistant-addons).
I believe the issue from what I've seen is that the default mosquito add-on has issues with certain characters but this one uses a sqlite database I think which resolves the issues.
I verified it worked by connecting my phone to it from a compatible app but I still haven't got cync2mqtt connected to it.
I'm running it off of my main machine which is running arch.

**Comment by zimmra** [comment]
Eureka!
Enabled unrestricted access, detailed in the addon instructions

Add the following configuration to enable unrestricted access to all topics.

Enable the customize flag
```
  customize:
    active: true
    folder: mosquitto
```
Create /share/mosquitto/acl.conf with the contents:
```
acl_file /share/mosquitto/accesscontrollist
```

Create /share/mosquitto/accesscontrollist with the contents:
```
user [YOUR_MQTT_USER]
topic readwrite #
```

Not optimal, but it works now. Not sure if I'll dig deeper into why it doesn't work 'restricted', not my expertise really.

**Comment by zimmra** [comment]
Gonna close this as it's not a cync2mqtt issue, but an issue with the HASS OS Mosquitto Addon
