### ISSUE TITLE
systemctl service fails to load cync2mqtt upon reboot

### ISSUE THREAD

**Issue by zimmra** [juanboro/cync2mqtt#8]
```
pi@zPI:~ $ sudo systemctl status cync2mqtt
* cync2mqtt.service - cync2mqtt
     Loaded: loaded (/etc/systemd/system/cync2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-16 18:47:14 PST; 1min 13s ago
   Main PID: 415 (cync2mqtt)
      Tasks: 2 (limit: 8771)
        CPU: 1.227s
     CGroup: /system.slice/cync2mqtt.service
             `-415 /home/pi/venv/cync2mqtt/bin/python3 /home/pi/venv/cync2mqtt/bin/cync2mqtt /home/pi/cync_mesh.yaml

Dec 16 18:47:14 zPI systemd[1]: Started cync2mqtt.
Dec 16 18:47:17 zPI cync2mqtt[566]: MQTT connection failed: OSError(101, 'Network is unreachable')
Dec 16 18:47:17 zPI cync2mqtt[566]: Connection failed: ConnectException(OSError(101, 'Network is unreachable'))
Dec 16 18:47:17 zPI cync2mqtt[566]: 2021-12-16 18:47:17,424 - cync2mqtt - ERROR - MQTT Connection failed: [Errno 101] Network is unreachable
Dec 16 18:47:17 zPI cync2mqtt[566]: Client session is not currently connected, ignoring call
Dec 16 18:47:17 zPI cync2mqtt[566]: 2021-12-16 18:47:17,424 - cync2mqtt - ERROR - Will attempt reconnect in 10 minutes
```

Uses the systemctl service definition you have posted in the readme
doing a `sudo systemctl restart cync2mqtt` after re-SSHing in gets it up and running

**Comment by juanboro** [comment]
I'm not sure about this - someone who is more knowledgeable on systemd might be.  From my limited systemd knowledge - the After=network.target part should tell it to not start till after networking is up.  As it is ---after 10 minutes does it self correct itself and connect?  Is something adding network routes after the standard rasberry pi os networking comes on?

**Comment by zimmra** [comment]
I'm going to close this as it doesn't seem like an inherent problem with cync2mqtt

My current implementation doesn't run this on a dedicated RPi anymore, I've got this running directly on my amd64/x86_64 HASS OS machine via a docker container (HASS addon) based on alpine linux.
https://github.com/zimmra/cync2mqtt-docker 
Super scrapily put together, but it works surprisingly well.
