### ISSUE TITLE
Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt

### ISSUE THREAD

**Issue by zimmra** [juanboro/cync2mqtt#9]
Now that I'm actually connecting, seems to be an error from the config being sent. 

These bulbs don't support RGB, but it is listed as a color mode in the error. Regardless, they do not successfully populate as entites. 

The below error happens for each bulb
## Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt
`Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Vanity 4', 'command_topic': 'acyncmqtt/set/44ADB1815E67/27', 'state_topic': 'acyncmqtt/status/44ADB1815E67/27', 'availability_topic': 'acyncmqtt/availability/44ADB1815E67/27', 'payload_available': 'online', 'payload_not_available': 'offline', 'unique_id': 'A4C138E83FF1', 'schema': 'json', 'brightness': True, 'brightness_scale': 100, 'color_mode': True, 'supported_color_modes': ['brightness', 'onoff', 'color_temp', 'rgb'], 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 210, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 38, in validate_mqtt_light_discovery return schemas[value[CONF_SCHEMA]](value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run return self._exec(self._compiled, value, path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec v = func(path, v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 97, in valid_supported_color_modes raise vol.Error(f"Invalid supported_color_modes {sorted(color_modes)}") voluptuous.error.Error: Invalid supported_color_modes ['brightness', 'color_temp', 'onoff', 'rgb']`

**Comment by zimmra** [comment]
I _think_ Home Assistant/the HA MQTT integration is maybe looking for just one color_mode? Can't find anything that definitively says so, but I think:
it assumes rgb has capabilities of color_temp, brightness, and onoff
it assumes color_temp has capabilities of brightness, and onoff
it assumes brightness has capabilities of onoff

I could be wrong, but I can't find an example that has more than one color_mode in the supported_color_modes field, they all seem to use just one in what I have seen since looking into problem

**Comment by juanboro** [comment]
I _think_ you probably are right -- I'll take a look tonight.  None of my cync bulbs have temp/color -- but I have other integrations that do... will take a look at how they work on my network.

**Comment by juanboro** [comment]
Ok - I think I've partially fixed it.  The exception hopefully won't happen now.

  What I think you may see a problem with is the temperature scale may not be right.  If it's wrong can you run with debug log-level and see when you set the temperature in the Cync app to both extremes what values pub_worker is sending?  I'll also take a look at the Telink documentation as well if needed.

For reference on the color mode:
it assumes rgb has capabilities of brightness, and onoff
it assumes color_temp has capabilities of brightness, and onoff
it assumes brightness has capabilities of onoff

So you can set rgb and/or color_temp (I also had a bug on setting rgb i fixed).  But you can't set on/off or brightness if either rgb or color-temp is set.

**Comment by zimmra** [comment]
Yeah seems to work connect/discover fine now. 
Temperature adjustment doesn't do anything currently. I should be able to pull some more info tonight. I'll make a separate issue for that, since the discovery portion seems to be good now.
